version: "3.9"
    
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer:
    depends_on:
      - db
    image: adminer:latest
    ports:
      - "127.0.0.1:8042:8080"
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - type: bind
        source: ./sdw_01
        target: /var/www/html/wp-content/plugins/sdw_01
      - type: bind
        source: ./sdw_02
        target: /var/www/html/wp-content/plugins/sdw_02
      - type: bind
        source: ./sdw_04
        target: /var/www/html/wp-content/plugins/sdw_04
      - type: bind
        source: ./sdw_05
        target: /var/www/html/wp-content/plugins/sdw_05
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}